### ISSUE TITLE
Freezing while loading

### ISSUE THREAD

**Issue by osa519** [erkle64/Unfoundry#3]
The game freezes on loading before the Main Menu.
Couldn't find anywhere else to report this, but it may very well be a User error, but this is what I see in the player logs. 

`Loading Mods from: C:\Program Files (x86)\Steam\steamapps\common\FOUNDRY\Mods
Fallback handler could not load library C:/Program Files (x86)/Steam/steamapps/common/FOUNDRY/Foundry_Data/MonoBleedingEdge/data-0000022C76244010.dll
Submitting error report:
  Session Time = 0 minutes
Submitting error report.
Error report submitted successfully.
Could not load Mod:Mods\A_Unfoundry
Error:System.MissingMethodException: Method not found: void .AddSystemToGameSimulation..ctor()
  at (wrapper managed-to-native) `

**Comment by erkle64** [comment]
I've not been able to reproduce the error.  Could you please attach a full log file?

**Comment by osa519** [comment]
Yep
[Player.log](https://github.com/user-attachments/files/16432701/Player.log)

**Comment by osa519** [comment]
I figured that was the issue. I did just came back and updated it. I'll delete everything and do a full reinstall this time. Thanks.
